<!--
  BambooMintKey - Vietnamese Telex Input Method Editor for Windows
  Copyright (c) 2026 Dương Gia Long and LMO contributors
  SPDX-License-Identifier: MIT
-->
<Project>
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    
    <!-- Thông tin bản quyền & Metadata -->
    <Company>BambooMintKey</Company>
    <Authors>BambooMintKey Contributors</Authors>
    <Product>BambooMintKey Vietnamese Input</Product>
    <Copyright>Copyright © 2026</Copyright>
  </PropertyGroup>
</Project>